version: '3'
services:

    service:
        image: app-test-img
        build: .
        env_file: .env
        environment:
            - PYTHONPATH=/app
        command: python src/
        tty: true
        user: root
        working_dir: /app
        volumes:
            - .:/app
        #ports:
        #    - "8000:8000"

